import Footer from "./components/footer/Footer";
import Navbar from "./components/navbar/Navbar";
import "./globals.css";

import { Noto_Sans_Armenian } from "next/font/google";
const noto = Noto_Sans_Armenian({ subsets: ["latin"] });

export const metadata = {
  title: "Blog Guru",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={noto.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
};
export default RootLayout;
